"""empty message

Revision ID: 3540bf03d7a8
Revises: ceee07e2e232
Create Date: 2021-02-20 04:21:20.276428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3540bf03d7a8'
down_revision = 'ceee07e2e232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    conn = op.get_bind()
    schemas = conn.execute("SELECT schema_name FROM information_schema.schemata WHERE schema_name NOT IN ('information_schema', 'pg_catalog','pg_toast', 'pg_temp_1', 'pg_toast_temp_1','public')").fetchall()
    schemas = [ str(x[0]) for x in schemas]
    for schema in schemas:
        print("Executing on schema {}".format(schema))
        op.execute("SET search_path TO {}".format(schema))
        
        op.create_table('credit_notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('shift_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('qty', sa.Float(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('vehicle_number', sa.String(), nullable=True),
        sa.Column('driver_name', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        
    
        op.create_table('debit_notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shift_id', sa.Integer(), nullable=False),
        sa.Column('tank_id', sa.Integer(), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('qty', sa.Float(), nullable=False),
        sa.Column('cost_price', sa.Float(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('document_number', sa.String(), nullable=True),
        sa.Column('supplier', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
        sa.ForeignKeyConstraint(['supplier'], ['supplier.id'], ),
        sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.execute("SET search_path TO default")
    op.execute("SET search_path TO default")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
   
    op.drop_table('debit_notes', schema='tenant')
   
    op.drop_table('credit_notes', schema='tenant')
     # ### end Alembic commands ###
