"""customer txns columns

Revision ID: 5e9d7d26239a
Revises: 0edc0e77c0e5
Create Date: 2021-04-04 17:52:24.571316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9d7d26239a'
down_revision = '0edc0e77c0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    schemas = conn.execute("SELECT schema_name FROM information_schema.schemata WHERE schema_name NOT IN ('information_schema', 'pg_catalog','pg_toast', 'pg_temp_1', 'pg_toast_temp_1','public')").fetchall()
    schemas = [ str(x[0]) for x in schemas]
    for schema in schemas:
        print("Executing on schema {}".format(schema))
        op.execute("SET search_path TO {}".format(schema))
        op.add_column('credit_notes',sa.Column('customer_txn_id', sa.Integer(), nullable=True))
        op.add_column('invoices',sa.Column('customer_txn_id', sa.Integer(), nullable=True))
        op.add_column('customer_payments',sa.Column('customer_txn_id', sa.Integer(), nullable=True))
        op.add_column('debit_notes',sa.Column('supplier_txn_id', sa.Integer(), nullable=True))
        op.add_column('delivery',sa.Column('supplier_txn_id', sa.Integer(), nullable=True))
        op.add_column('supplier_payments',sa.Column('supplier_txn_id', sa.Integer(), nullable=True))
        op.create_foreign_key('credit_notes_customer_txn_fkey', 'credit_notes', 'customer_transactions', ['customer_txn_id'], ['id'])
        op.create_foreign_key('invoices_customer_txn_fkey', 'invoices', 'customer_transactions', ['customer_txn_id'], ['id'])
        op.create_foreign_key('customer_payments_customer_txn_fkey', 'customer_payments', 'customer_transactions', ['customer_txn_id'], ['id'])
        op.create_foreign_key('debit_notes_supplier_txn_fkey', 'debit_notes', 'supplier_transactions', ['supplier_txn_id'], ['id'])
        op.create_foreign_key('delivery_supplier_txn_fkey', 'delivery', 'supplier_transactions', ['supplier_txn_id'], ['id'])
        op.create_foreign_key('supplier_payments_supplier_txn_fkey', 'supplier_payments', 'supplier_transactions', ['supplier_txn_id'], ['id'])
        op.execute("SET search_path TO default")
    op.execute("SET search_path TO default")



    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', schema='public', type_='foreignkey')
    op.create_foreign_key('subscriptions_package_fkey', 'subscriptions', 'packages', ['package'], ['id'])
    op.create_foreign_key('subscriptions_tenant_id_fkey', 'subscriptions', 'tenants', ['tenant_id'], ['id'])
    op.drop_table('pump_readings', schema='tenant')
    op.drop_table('tank_dips', schema='tenant')
    op.drop_table('supplier_payments', schema='tenant')
    op.drop_table('pumps', schema='tenant')
    op.drop_table('ledger', schema='tenant')
    op.drop_table('invoices', schema='tenant')
    op.drop_table('delivery', schema='tenant')
    op.drop_table('debit_notes', schema='tenant')
    op.drop_table('customer_payments', schema='tenant')
    op.drop_table('credit_notes', schema='tenant')
    op.drop_table('coupon_sales', schema='tenant')
    op.drop_table('tanks', schema='tenant')
    op.drop_table('supplier_transactions', schema='tenant')
    op.drop_table('prices', schema='tenant')
    op.drop_table('lube_qty', schema='tenant')
    op.drop_table('journals_pending', schema='tenant')
    op.drop_table('journals', schema='tenant')
    op.drop_table('customer_transactions', schema='tenant')
    op.drop_table('coupons', schema='tenant')
    op.drop_table('users', schema='tenant')
    op.drop_table('supplier', schema='tenant')
    op.drop_table('sales_receipts', schema='tenant')
    op.drop_table('products', schema='tenant')
    op.drop_table('payouts', schema='tenant')
    op.drop_table('lubes_cash_up', schema='tenant')
    op.drop_table('customers', schema='tenant')
    op.drop_table('cash_up', schema='tenant')
    op.drop_table('shift_underway', schema='tenant')
    op.drop_table('shift', schema='tenant')
    op.drop_table('accounts', schema='tenant')
    # ### end Alembic commands ###
