"""empty message

Revision ID: c47f1c53a662
Revises: bc8958b97994
Create Date: 2020-11-15 16:33:52.813448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47f1c53a662'
down_revision = 'bc8958b97994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()
    schemas = conn.execute("SELECT schema_name FROM information_schema.schemata WHERE schema_name NOT IN ('information_schema','public', 'pg_catalog','pg_toast', 'pg_temp_1', 'pg_toast_temp_1')").fetchall()
    schemas = [str(x[0]) for x in schemas]
    for schema in schemas:
        conn.execute("SET search_path TO {}".format(schema))
        op.add_column('invoices', sa.Column('timestamp', sa.DateTime(),server_default=sa.func.now()))
        op.add_column('customer_payments', sa.Column('timestamp', sa.DateTime(),server_default=sa.func.now()))

    conn.execute("SET search_path TO public")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', sa.Column('timestamp', sa.DateTime()))
    op.drop_column('customer_payments', sa.Column('timestamp', sa.DateTime()))
    # ### end Alembic commands ###
