"""empty message

Revision ID: ceee07e2e232
Revises: 5989646a4b50
Create Date: 2021-02-14 19:47:37.735793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceee07e2e232'
down_revision = '5989646a4b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    schemas = conn.execute("SELECT schema_name FROM information_schema.schemata WHERE schema_name NOT IN ('information_schema', 'pg_catalog','pg_toast', 'pg_temp_1', 'pg_toast_temp_1','public')").fetchall()
    schemas = [ str(x[0]) for x in schemas]
    for schema in schemas:
        print("Executing on schema {}".format(schema))
        op.execute("SET search_path TO {}".format(schema))
        op.add_column('coupons',sa.Column('customer_id', sa.Integer(),nullable=True))
        op.create_foreign_key('coupons_customers_fkey', 'coupons', 'customers', ['customer_id'], ['id'])
        op.execute("SET search_path TO default")
    op.execute("SET search_path TO default")
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    schemas = conn.execute("SELECT schema_name FROM information_schema.schemata WHERE schema_name NOT IN ('information_schema', 'pg_catalog','pg_toast', 'pg_temp_1', 'pg_toast_temp_1','public')").fetchall()
    schemas = [ str(x[0]) for x in schemas]
    for schema in schemas:
        print("Executing on schema {}".format(schema))
        op.execute("SET search_path TO {}".format(schema))
        op.drop_column('coupons','account_id')
        #op.drop_constraint("coupons_accounts_fkey",type_="foreignkey", table_name="coupons")
        op.execute("SET search_path TO default")
    op.execute("SET search_path TO default")
    
    
    # ### end Alembic commands ###
